Repository lap-winder/docs, pull requests merged in 2021-12, with the labels that each got.

#8 [Write] docs/README.md
  README.md
Labels: documentation

#10 [Upload] convention documents
  conventions/code-review/Code-Review-Conventions.md
  conventions/coding/Coding-Conventions.md
  conventions/development/Development-Conventions.md
  conventions/documentation/Documentation-Conventions.md
Labels: documentation

#14 Add Issue template (#12)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/document.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/hotfix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/style.md
Labels: Document

#13 Docs: #12 Create git-workflow.md
  git/git-forking-workflow.md
Labels: Document

#15 #12 Write Git workflow overview
  git/git-forking-workflow.md
Labels: Document

#17 (#16)Add winder api server login & register controllers
  api-server/emailVerifyController.js
  api-server/kakaoOauthController.js
  api-server/loginController.js
  api-server/naverOauthController.js
  api-server/registerController.js
Labels: Document, Refactor

#20 Docs: How to install jenkins on ec2 (#19)
  ci-cd/README.md
  ci-cd/sources/setup.sh
Labels: Document
